"""Common AWS Constants"""

MOCK_AWS_ACCOUNT_ARN = 'arn:aws:iam::123456789012:user/Alice'
MOCK_AWS_ACCOUNT_ID = 'permanentuser'
MOCK_AWS_ACCOUNT_SECRET_KEY = 'FAKEFAKEFAKEFAKEFAKEfakefakefakefakefake'

MOCK_AWS_TEMP_ACCOUNT_ARN = 'arn:aws:iam::123456789012:user/Bob'
MOCK_AWS_TEMP_ACCOUNT_ID = 'tempuser'
MOCK_AWS_TEMP_ACCOUNT_SECRET_KEY = 'fakefakefakefakefakeFAKEFAKEFAKEFAKEFAKE'
MOCK_AWS_TEMP_ACCOUNT_SESSION_TOKEN = 'FAKETEMPORARYSESSIONTOKENfaketemporarysessiontoken'
