import itertools

HEADER = '''# Autogenerated tests that transient errors in a transaction unpin the session.
# See mongos-unpin-tests.py
topology: [sharded]
database_name: &database_name "transaction-tests"
collection_name: &collection_name "test"

data: &data
  - {_id: 1}
  - {_id: 2}

tests:
  - description: remain pinned after non-transient Interrupted error on insertOne
    useMultipleMongoses: true
    operations:
      - &startTransaction
        name: startTransaction
        object: session0
      - &initialCommand
        name: insertOne
        object: collection
        arguments:
          session: session0
          document: {_id: 3}
        result:
          insertedId: 3
      - name: targetedFailPoint
        object: testRunner
        arguments:
          session: session0
          failPoint:
            configureFailPoint: failCommand
            mode: {times: 1}
            data:
              failCommands: ["insert"]
              errorCode: 11601
      - name: insertOne
        object: collection
        arguments:
          session: session0
          document:
            _id: 4
        result:
          errorLabelsContain: ["TransientTransactionError"]
          errorLabelsOmit: ["UnknownTransactionCommitResult"]
      - &assertSessionPinned
        name: assertSessionPinned
        object: testRunner
        arguments:
          session: session0
      - &commitTransaction
        name: commitTransaction
        object: session0

    expectations:
      - command_started_event:
          command:
            insert: *collection_name
            documents:
              - _id: 3
            ordered: true
            readConcern:
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction: true
            autocommit: false
            writeConcern:
          command_name: insert
          database_name: *database_name
      - command_started_event:
          command:
            insert: *collection_name
            documents:
              - _id: 4
            ordered: true
            readConcern:
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction:
            autocommit: false
            writeConcern:
          command_name: insert
          database_name: *database_name
      - command_started_event:
          command:
            commitTransaction: 1
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction:
            autocommit: false
            writeConcern:
            recoveryToken: 42
          command_name: commitTransaction
          database_name: admin

    outcome: &outcome
      collection:
        data:
          - {_id: 1}
          - {_id: 2}
          - {_id: 3}
          - {_id: 4}

  - description: unpin after transient error within a transaction
    useMultipleMongoses: true
    operations:
      - &startTransaction
        name: startTransaction
        object: session0
      - &initialCommand
        name: insertOne
        object: collection
        arguments:
          session: session0
          document:
            _id: 3
        result:
          insertedId: 3
      - name: targetedFailPoint
        object: testRunner
        arguments:
          session: session0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
              failCommands: ["insert"]
              closeConnection: true
      - name: insertOne
        object: collection
        arguments:
          session: session0
          document:
            _id: 4
        result:
          errorLabelsContain: ["TransientTransactionError"]
          errorLabelsOmit: ["UnknownTransactionCommitResult"]
      # Session unpins from the first mongos after the insert error and
      # abortTransaction succeeds immediately on any mongos.
      - &assertSessionUnpinned
        name: assertSessionUnpinned
        object: testRunner
        arguments:
          session: session0
      - &abortTransaction
        name: abortTransaction
        object: session0

    expectations:
      - command_started_event:
          command:
            insert: *collection_name
            documents:
              - _id: 3
            ordered: true
            readConcern:
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction: true
            autocommit: false
            writeConcern:
          command_name: insert
          database_name: *database_name
      - command_started_event:
          command:
            insert: *collection_name
            documents:
              - _id: 4
            ordered: true
            readConcern:
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction:
            autocommit: false
            writeConcern:
          command_name: insert
          database_name: *database_name
      - command_started_event:
          command:
            abortTransaction: 1
            lsid: session0
            txnNumber:
              $numberLong: "1"
            startTransaction:
            autocommit: false
            writeConcern:
            recoveryToken: 42
          command_name: abortTransaction
          database_name: admin

    outcome: &outcome
      collection:
        data: *data

  # The rest of the tests in this file test every operation type against
  # multiple types of transient errors (connection and error code).'''

TEMPLATE = '''
  - description: {test_name} {error_name} error on {op_name}
    useMultipleMongoses: true
    operations:
      - *startTransaction
      - *initialCommand
      - name: targetedFailPoint
        object: testRunner
        arguments:
          session: session0
          failPoint:
            configureFailPoint: failCommand
            mode: {{times: 1}}
            data:
              failCommands: ["{command_name}"]
              {error_data}
      - name: {op_name}
        object: {object_name}
        arguments:
          session: session0
          {op_args}
        result:
          {error_labels}: ["TransientTransactionError"]
      - *{assertion}
      - *abortTransaction
    outcome: *outcome
'''


OPS = {
    'insertOne': ('insert', 'collection', r'document: {_id: 4}'),
    'insertMany': ('insert', 'collection', r'documents: [{_id: 4}, {_id: 5}]'),
}

NON_TRANSIENT_ERRORS = {
    'Interrupted': 'errorCode: 11601',
}

TRANSIENT_ERRORS = {
    'connection': 'closeConnection: true',
    'ShutdownInProgress': 'errorCode: 91',
}


def create_pin_test(op_name, error_name):
    test_name = 'remain pinned after non-transient'
    assertion = 'assertSessionPinned'
    error_labels = 'errorLabelsOmit'
    command_name, object_name, op_args = OPS[op_name]
    error_data = NON_TRANSIENT_ERRORS[error_name]
    return TEMPLATE.format(**locals())


def create_unpin_test(op_name, error_name):
    test_name = 'unpin after transient'
    assertion = 'assertSessionUnpinned'
    error_labels = 'errorLabelsContain'
    command_name, object_name, op_args = OPS[op_name]
    error_data = TRANSIENT_ERRORS[error_name]
    return TEMPLATE.format(**locals())

tests = []
for op_name, error_name in itertools.product(OPS, NON_TRANSIENT_ERRORS):
    tests.append(create_pin_test(op_name, error_name))
for op_name, error_name in itertools.product(OPS, TRANSIENT_ERRORS):
    tests.append(create_unpin_test(op_name, error_name))

print(HEADER)
print(''.join(tests))
